name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  socket_io_client: ^3.0.2
  flutter_local_notifications: ^18.0.1
  flutter_chat_ui: ^1.6.15
  emoji_picker_flutter: ^1.6.4
  image_picker: ^1.0.8
  file_picker: ^8.0.0+1
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  flutter_secure_storage: ^9.2.4
  uuid: ^4.2.2
  timeago: ^3.7.0
  get: 4.6.6
  flutter: 
    sdk: flutter
  window_manager: ^0.4.3
  intl: ^0.19.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets\logo_metm.png